# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
- release
- devel

r_github_packages:
#  - DoseResponse/drcData
  - r-lib/covr

after_success:
  - Rscript -e 'covr::codecov()'
